name: MonstersVsKingsmen
main: plugin.monstersvskingsmen.MonstersVsKingsmen
version: 0.0.1
api-version: 1.16
commands:
  startgame:
    description: This is the command to start the game.
    usage: /<command>
  resetgame:
    description: This is the command to reset the game.
    usage: /<command>