name: MonstersVsKingsmen
main: plugin.monstersvskingsmen.MonstersVsKingsmen
version: 0.0.1
api-version: 1.16
commands:
  startgame:
    description: This is the command to start the game.
    usage: /<command>
  destroyworld:
    description: This is the command to destroy the map.
    usage: /<command>
  buildworld:
    description: This is the command to build a map.
    usage: /<command>
  rules:
    description: This is the command to obtain the rule book.
    usage: /<command>
  spawndragon:
    description: This is the command to manually spawn in a dragon.
    usage: /<command>